# Generated by Django 2.2 on 2020-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedAddService', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('cnt', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TvLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv1name', models.CharField(blank=True, max_length=300)),
                ('tv1link', models.CharField(blank=True, max_length=300)),
                ('tv1ylink', models.CharField(blank=True, max_length=300)),
                ('tv2name', models.CharField(blank=True, max_length=300)),
                ('tv2link', models.CharField(blank=True, max_length=300)),
                ('tv2ylink', models.CharField(blank=True, max_length=300)),
                ('tv3name', models.CharField(blank=True, max_length=300)),
                ('tv3link', models.CharField(blank=True, max_length=300)),
                ('tv3ylink', models.CharField(blank=True, max_length=300)),
                ('tv4name', models.CharField(blank=True, max_length=300)),
                ('tv4link', models.CharField(blank=True, max_length=300)),
                ('tv4ylink', models.CharField(blank=True, max_length=300)),
                ('tv5name', models.CharField(blank=True, max_length=300)),
                ('tv5link', models.CharField(blank=True, max_length=300)),
                ('tv5ylink', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
