# Generated by Django 2.2 on 2020-02-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1name', models.CharField(max_length=100)),
                ('team2name', models.CharField(max_length=100)),
                ('team1logo', models.ImageField(max_length=900, upload_to='images/')),
                ('team2logo', models.ImageField(max_length=900, upload_to='images/')),
                ('matchdate', models.DateField()),
                ('matchtime', models.TimeField()),
                ('matchvenue', models.CharField(max_length=255)),
            ],
        ),
    ]
