# Generated by Django 2.2 on 2020-02-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_matchschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchschedule',
            name='team1logo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='matchschedule',
            name='team2logo',
            field=models.FileField(upload_to=''),
        ),
    ]
