# Generated by Django 2.2 on 2020-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_matchnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PslTvLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv1name', models.CharField(blank=True, max_length=300)),
                ('tv1link', models.CharField(blank=True, max_length=300)),
                ('tv1ylink', models.CharField(blank=True, max_length=300)),
                ('tv2name', models.CharField(blank=True, max_length=300)),
                ('tv2link', models.CharField(blank=True, max_length=300)),
                ('tv2ylink', models.CharField(blank=True, max_length=300)),
                ('tv3name', models.CharField(blank=True, max_length=300)),
                ('tv3link', models.CharField(blank=True, max_length=300)),
                ('tv3ylink', models.CharField(blank=True, max_length=300)),
                ('tv4name', models.CharField(blank=True, max_length=300)),
                ('tv4link', models.CharField(blank=True, max_length=300)),
                ('tv4ylink', models.CharField(blank=True, max_length=300)),
                ('tv5name', models.CharField(blank=True, max_length=300)),
                ('tv5link', models.CharField(blank=True, max_length=300)),
                ('tv5ylink', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
