# Generated by Django 2.2 on 2020-02-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_psltvlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='IplMatchSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1name', models.CharField(max_length=100)),
                ('team2name', models.CharField(max_length=100)),
                ('team1logo', models.FileField(upload_to='')),
                ('team2logo', models.FileField(upload_to='')),
                ('matchdate', models.DateField()),
                ('matchtime', models.TimeField()),
                ('matchvenue', models.CharField(max_length=255)),
            ],
        ),
    ]
