# Generated by Django 2.2 on 2020-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_iplmatchschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplmatchschedule',
            name='match_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchschedule',
            name='match_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
