# Generated by Django 2.2 on 2020-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20200226_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='VERSION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VERSION', models.IntegerField()),
            ],
        ),
    ]
