# Generated by Django 2.2 on 2020-02-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='VERSION',
            new_name='version',
        ),
    ]
