# Generated by Django 2.2 on 2020-03-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_player_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['player_name']},
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='profiles_api.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=45),
        ),
    ]
