# Generated by Django 2.2 on 2020-03-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_auto_20200306_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_name',
            new_name='team',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'player_name')},
        ),
    ]
