# Generated by Django 2.2 on 2020-03-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_auto_20200306_2109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
    ]
