# Generated by Django 2.2 on 2020-03-06 21:28

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_auto_20200306_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[120, 120], upload_to='image'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='profiles_api.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[120, 120], upload_to='image'),
        ),
    ]
