# Generated by Django 2.2 on 2020-03-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0014_auto_20200306_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_image',
        ),
    ]
